In [1]:
import sys
import pandas as pd
from datetime import datetime
sys.path.insert(0, './Moduulit')
pd.options.mode.chained_assignment = None
# Importtaus tässä muodossa
from database_connection import database_query
from outliers import find_outliers, draw_histogram
from clean_dataframe import clean_dataframe
from write_df_to_database import write_df_to_mariadb
from xy_diskretisointi import xy_to_grid
from isolation_forest import *
from sisään_uloskäynnit import *
from clean_velocities import *

# tai from ... import *


# Jos datasetti on "df"

# Esim. find_outliers(df)
# Esim. draw_histogram(df['x'], df['y'], 20) <-- kolmas meinaa bins arvoa, eli histogrammin "rakeisuutta"

In [2]:
df = pd.read_csv('projekti2.csv')
df

,Unnamed: 0,node_id,timestamp,x,y,z,q
0,0,b'-2393099149039893833',b'2020-06-24 12:20:08.533016+00:00',2762,-257,100,0
1,1,b'-2393099149039893833',b'2020-06-24 12:20:08.620015+00:00',2870,-344,100,0
2,2,b'-2393099149039893833',b'2020-06-24 12:20:09.622827+00:00',2916,-344,100,0
3,3,b'-2393099149039893833',b'2020-06-24 12:20:09.622846+00:00',2894,-254,100,0
4,4,b'-2393099149039893833',b'2020-06-24 12:20:10.116102+00:00',2888,-188,100,0
...,...,...,...,...,...,...,...
13890901,13890901,b'4996252679627069957',b'2020-06-01 03:00:05.469336+00:00',635,1064,0,0
13890902,13890902,b'4996252679627069957',b'2020-06-01 03:00:06.47926+00:00',681,760,0,0
13890903,13890903,b'4996252679627069957',b'2020-06-01 03:00:08.507118+00:00',622,991,0,0
13890904,13890904,b'4996252679627069957',b'2020-06-01 03:00:09.547553+00:00',644,1066,0,0
13890905,13890905,b'4996252679627069957',b'2020-06-01 03:00:10.968327+00:00',634,1054,0,0

In [3]:
df = df.sort_values(by='timestamp', ascending=True)

In [4]:
dates = df['timestamp']

In [5]:
dates

12502166    b'2020-05-05 17:48:36.098033+00:00'
12502167    b'2020-05-05 17:48:40.095929+00:00'
12502168    b'2020-05-05 17:50:13.095937+00:00'
12502169    b'2020-05-05 17:50:15.095536+00:00'
12502170    b'2020-05-05 17:50:17.099466+00:00'
                           ...
5262600      b'2020-10-23 06:57:49.37178+00:00'
11869220    b'2020-10-23 06:57:49.988599+00:00'
583873      b'2020-10-23 06:57:50.988798+00:00'
1210149     b'2020-10-23 06:57:54.757935+00:00'
6012291     b'2020-10-23 06:57:56.988597+00:00'
Name: timestamp, Length: 13890906, dtype: object