In [3]:
import numpy as np
import pylab as plt
import pandas as pd
import mysql.connector

mydb = mysql.connector.connect(
  host="172.28.200.50",
  port=3306,
  user="root",
  passwd="insert-password-here",
  database="iiwari_org")


mycursor = mydb.cursor(dictionary=True)
mycursor.execute("SELECT DISTINCT node_id FROM SensorData;" );
df = pd.DataFrame(mycursor.fetchall())
df

                    node_id
0   b'-2393099149039893833'
1   b'-2393099149039893844'
2   b'-2393099149039893848'
3   b'-2393099149039893859'
4   b'-2393099149039893963'
5   b'-2393099149039893967'
6   b'-2393099149039894097'
7   b'-2393099149039894112'
8   b'-2393099149039894120'
9   b'-2393099149039894124'
10  b'-2393099149039894127'
11  b'-2393099149039894248'
12  b'-2393099149039894352'
13  b'-2393099149039894356'
14  b'-2393099149039894370'